from .label_instructions import *
from .rd_imm_instructions import *
from .rd_instructions import *
from .rd_rs_rt_instructions import *
from .rs_instructions import *
from .rs_label_instructions import *
from .rs_mem_instructions import *
from .rs_rt_imm_instructions import *
from .rs_rt_instructions import *
from .rs_rt_label_instructions import *
from .special_instructions import *
