"""dashmips package."""

import dashmips.instructions.label_instructions
import dashmips.instructions.rd_imm_instructions
import dashmips.instructions.rd_instructions
import dashmips.instructions.rd_rs_rt_instructions
import dashmips.instructions.rs_instructions
import dashmips.instructions.rs_label_instructions
import dashmips.instructions.rs_mem_instructions
import dashmips.instructions.rs_rt_imm_instructions
import dashmips.instructions.rs_rt_instructions
import dashmips.instructions.rs_rt_label_instructions
import dashmips.instructions.special_instructions

import dashmips.syscalls.print_syscalls
