name: Dashmips

on:
  push:
    branches:
      - master
      - "feature/**"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          source $HOME/.poetry/env
      - name: Install Dependencies
        run: |
          source $HOME/.poetry/env
          poetry install
      - name: Test with pytest
        run: |
          source $HOME/.poetry/env
          poetry run pytest
